In [93]:
import numpy as np
from sklearn import datasets

In [94]:
mydata=datasets.load_iris()

In [95]:
mydata=datasets.load_iris()

In [96]:
x_input=mydata.data

In [97]:
y_output=mydata.target

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x_input,y_output,test_size=.8)#test size to split the data ,random state to fix the value of parameter random_state=20 after test size

In [100]:
x_train.shape

(30, 4)

In [101]:
x_train

array([[ 5.5,  4.2,  1.4,  0.2],
       [ 6.7,  3.1,  5.6,  2.4],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 6.5,  2.8,  4.6,  1.5],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 6.4,  2.7,  5.3,  1.9],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 6.7,  3.1,  4.7,  1.5],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 5.3,  3.7,  1.5,  0.2],
       [ 5.6,  2.8,  4.9,  2. ],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 6.6,  3. ,  4.4,  1.4],
       [ 5.4,  3. ,  4.5,  1.5],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 6.1,  2.9,  4.7,  1.4],
       [ 4.5,  2.3,  1.3,  0.3],
       [ 5.9,  3. ,  5.1,  1.8],
       [ 6.6,  2.9,  4.6,  1.3],
       [ 7.6,  3. ,  6.6,  2.1],
       [ 4.9,  2.4,  3.3,  1. ]])

In [102]:
from sklearn.naive_bayes import GaussianNB

In [103]:
mygnc=GaussianNB()

In [104]:
mymodel=mygnc.fit(x_train,y_train)

In [105]:
yp=mymodel.predict(x_test)

In [106]:
ya=y_test

In [107]:
from sklearn import metrics

In [108]:
metrics.accuracy_score(ya,yp)

0.94999999999999996

In [109]:
import pandas as pd

In [110]:
mydf=pd.DataFrame({"Av":ya,"Pre":yp})

In [111]:
mydf #Confusion matrix=for which input it is giving false

Av  Pre
0     2    2
1     2    2
2     1    1
3     2    2
4     2    1
5     2    2
6     0    0
7     1    1
8     1    1
9     0    0
10    1    1
11    1    1
12    2    2
13    2    2
14    1    1
15    1    1
16    1    1
17    2    2
18    1    1
19    2    2
20    0    0
21    2    2
22    1    1
23    1    1
24    1    1
25    2    1
26    1    1
27    0    0
28    1    1
29    2    2
..   ..  ...
90    2    2
91    1    1
92    1    1
93    2    2
94    2    2
95    2    2
96    1    1
97    2    2
98    1    1
99    0    0
100   1    1
101   0    0
102   2    2
103   1    1
104   1    1
105   2    2
106   0    0
107   2    2
108   2    2
109   0    0
110   0    0
111   0    0
112   0    0
113   0    0
114   2    2
115   0    0
116   2    2
117   0    0
118   0    0
119   1    1

[120 rows x 2 columns]

In [112]:
#if we remove random state accuracy will change according to test_size

In [113]:
from sklearn.neighbors import KNeighborsClassifier

In [114]:
myknn=KNeighborsClassifier()#created instance or object of knn

In [115]:
mymodel=myknn.fit(x_train,y_train)

In [116]:
ya=y_test

In [117]:
ya

array([2, 2, 1, 2, 2, 2, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 0, 2, 1,
       1, 1, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 2, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1,
       0, 1, 0, 1, 0, 2, 0, 2, 2, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 1, 2, 1,
       2, 0, 0, 2, 1, 1, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2,
       0, 2, 0, 0, 1])

In [118]:
yp=mymodel.predict(x_test)

In [119]:
yp

array([2, 2, 1, 2, 1, 2, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 2, 1,
       1, 1, 1, 1, 0, 1, 2, 2, 0, 1, 1, 2, 2, 1, 0, 2, 2, 1, 1, 2, 1, 0, 1,
       0, 1, 0, 1, 0, 2, 0, 2, 2, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 1, 2, 1,
       2, 0, 0, 2, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2,
       0, 2, 0, 0, 2])

In [120]:
ya-yp

array([ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1])

In [121]:
from sklearn import metrics

In [122]:
m = metrics.accuracy_score(yp,ya)

In [123]:
m

0.94166666666666665

In [124]:
#Hence , Gaussian Algorithm gives more accuracy than Knn Algorithm